user:
  name_maximum: 50
  email_maximum: 255
  password_minimum: 6
  gravatar_size: 80
  gravatar_size_2: 50
  page_size: 10
  faker_user_number: 99
  time_save: 2
post:
  content_length: 140
  size: 50
  picture_size: 5
  picture_size_width: 400
  picture_size_height: 400
